### PR TITLE
Add border control parameter

### LINKED ISSUE #11: Black border around the edge of the display
When using this library with the 2.9" B/W displays from GoodDisplay (GDEW029T5), the black border is very noticeable. This is outside the controllable pixels, but if you have graphics right up to the edge, this border will touch the black pixels.

The border is also there on the smaller 2.13" tri-color displays (eg. on the Adafruit 2.13" E-Ink FeatherWing), but it is not as noticeable, since most is covered by the edge of the screen.

It seems that the color of this border is controlled by the VBD bits in the CDI command of the startup sequence, but the datasheet for IL0373 seems to skip the description for those two bits.

There are a bit more info in the datasheet for GDEW029T5 (2.9" B/W) and GDEW029T5 (2.13" tri color) and it seems like the color of the border depends on other settings in addition to the two VBD bits.

My experimentation has resulted in:
VBD[1:0] = 0, 0 // black border on both, last byte in CDI 0x37
VBD[1:0] = 0, 1 // white border on tri color, black border on b/w, last byte in CDI 0x77
VBD[1:0] = 1, 0 // red border on try color, white border on b/w, last byte in CDI 0xB7
VBD[1:0] = 1, 1 // white border on both, last byte in CDI 0xF7

I think the last one (1, 1) is what they call floating, with the other settings that are used (DDX[0]=1).

I think "white" of "floating" will blend in best with the displays, if it was to be fixed, but an option to select this in CircuitPython when using this driver would be nice, since that would allow use cases where the edge isn't covered by a case to have the border follow the general background color used.

I can work on that and make a pull request if there is interest.

### PR DESCRIPTION
**Pull request by makermelissa**
Fixes #11.

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Thank you!

**Comment by aocole** [comment]
Thanks for doing this! That border was driving me crazy.

**Comment by hopkapi** [comment]
Nice job, though does anyone know if this has made it to the MagTag yet? I think it's the same controller/display, but I'm not sure how to invoke the border parameter on it.

**Comment by makermelissa** [comment]
> Nice job, though does anyone know if this has made it to the MagTag yet? I think it's the same controller/display, but I'm not sure how to invoke the border parameter on it.

I think it's embedded in the core in this file: https://github.com/adafruit/circuitpython/blob/main/ports/espressif/boards/adafruit_magtag_2.9_grayscale/board.c

**Comment by hopkapi** [comment]
While I'm probably just reading/understanding all of this wrong, I'm not too sure if it is/how it could be? The only commit I can see to that file that happened after this one was 8 hours ago, and it doesn't seem like it includes any of this stuff. Plus in the file I can't see any reference to a border, and the CDI is still the same `0x50, 1, 0x97` one before you updated it to `x50\x01\x17`.

**Pull request merged**
